// Pays du monde (liste exhaustive)
export const countries = [
  "Afghanistan", "Afrique du Sud", "Albanie", "Algérie", "Allemagne", "Andorre", "Angola",
  "Antigua-et-Barbuda", "Arabie saoudite", "Argentine", "Arménie", "Australie", "Autriche",
  "Azerbaïdjan", "Bahamas", "Bahreïn", "Bangladesh", "Barbade", "Belgique", "Bélize", "Bénin",
  "Bhoutan", "Biélorussie", "Birmanie", "Bolivie", "Bosnie-Herzégovine", "Botswana", "Brésil",
  "Brunéi", "Bulgarie", "Burkina Faso", "Burundi", "Cambodge", "Cameroun", "Canada",
  "Cap-Vert", "Chili", "Chine", "Chypre", "Colombie", "Comores", "Congo", "Corée du Nord",
  "Corée du Sud", "Costa Rica", "Côte d'Ivoire", "Croatie", "Cuba", "Danemark", "Djibouti",
  "Dominique", "Égypte", "Émirats arabes unis", "Équateur", "Érythrée", "Espagne", "Estonie",
  "Eswatini", "États-Unis", "Éthiopie", "Fidji", "Finlande", "France", "Gabon", "Gambie",
  "Géorgie", "Ghana", "Grèce", "Grenade", "Guatemala", "Guinée", "Guinée-Bissau", "Guinée équatoriale",
  "Guyana", "Haïti", "Honduras", "Hongrie", "Inde", "Indonésie", "Irak", "Iran", "Irlande",
  "Islande", "Israël", "Italie", "Jamaïque", "Japon", "Jordanie", "Kazakhstan", "Kenya",
  "Kirghizistan", "Kiribati", "Koweït", "Laos", "Lesotho", "Lettonie", "Liban", "Liberia",
  "Libye", "Liechtenstein", "Lituanie", "Luxembourg", "Macédoine du Nord", "Madagascar",
  "Malaisie", "Malawi", "Maldives", "Mali", "Malte", "Maroc", "Marshall", "Maurice",
  "Mauritanie", "Mexique", "Micronésie", "Moldavie", "Monaco", "Mongolie", "Monténégro",
  "Mozambique", "Namibie", "Nauru", "Népal", "Nicaragua", "Niger", "Nigeria", "Norvège",
  "Nouvelle-Zélande", "Oman", "Ouganda", "Ouzbékistan", "Pakistan", "Palaos", "Panama",
  "Papouasie-Nouvelle-Guinée", "Paraguay", "Pays-Bas", "Pérou", "Philippines", "Pologne",
  "Portugal", "Qatar", "République centrafricaine", "République démocratique du Congo",
  "République dominicaine", "République tchèque", "Roumanie", "Royaume-Uni", "Russie",
  "Rwanda", "Saint-Christophe-et-Niévès", "Sainte-Lucie", "Saint-Marin", "Saint-Vincent-et-les-Grenadines",
  "Salomon", "Salvador", "Samoa", "Sao Tomé-et-Principe", "Sénégal", "Serbie", "Seychelles",
  "Sierra Leone", "Singapour", "Slovaquie", "Slovénie", "Somalie", "Soudan", "Soudan du Sud",
  "Sri Lanka", "Suède", "Suisse", "Suriname", "Syrie", "Tadjikistan", "Tanzanie", "Tchad",
  "Thaïlande", "Timor oriental", "Togo", "Tonga", "Trinité-et-Tobago", "Tunisie",
  "Turkménistan", "Turquie", "Tuvalu", "Ukraine", "Uruguay", "Vanuatu", "Vatican",
  "Venezuela", "Vietnam", "Yémen", "Zambie", "Zimbabwe"
];

// Nationalités correspondantes (ex: "R.D.Congolaise" pour la RDC)
export const nationalities = [
  "Afghane", "Sud-africaine", "Albanaise", "Algérienne", "Allemande", "Andorrane", "Angolaise",
  "Antiguaise", "Saoudienne", "Argentine", "Arménienne", "Australienne", "Autrichienne",
  "Azerbaïdjanaise", "Bahaméenne", "Bahreïnie", "Bangladaise", "Barbadienne", "Belge",
  "Bélizienne", "Béninoise", "Bhoutanaise", "Biélorusse", "Birmane", "Bolivienne",
  "Bosnienne", "Botswanaise", "Brésilienne", "Brunéienne", "Bulgare", "Burkinabé",
  "Burundaise", "Cambodgienne", "Camerounaise", "Canadienne", "Cap-verdienne", "Chilienne",
  "Chinoise", "Chypriote", "Colombienne", "Comorienne", "Congolaise", "Nord-coréenne",
  "Sud-coréenne", "Costaricienne", "Ivoirienne", "Croate", "Cubaine", "Danoise", "Djiboutienne",
  "Dominiquaise", "Égyptienne", "Émirienne", "Équatorienne", "Érythréenne", "Espagnole",
  "Estonienne", "Eswatinienne", "Américaine", "Éthiopienne", "Fidjienne", "Finlandaise",
  "Française", "Gabonaise", "Gambienne", "Géorgienne", "Ghanéenne", "Grecque", "Grenadienne",
  "Guatémaltèque", "Guinéenne", "Bissau-guinéenne", "Équatoguinéenne", "Guyanienne",
  "Haïtienne", "Hondurienne", "Hongroise", "Indienne", "Indonésienne", "Irakienne",
  "Iranienne", "Irlandaise", "Islandaise", "Israélienne", "Italienne", "Jamaïcaine",
  "Japonaise", "Jordanienne", "Kazakhstanaise", "Kényane", "Kirghize", "Kiribatienne",
  "Koweïtienne", "Laotienne", "Lesothane", "Lettonne", "Libanaise", "Libérienne",
  "Libyenne", "Liechtensteinoise", "Lituanienne", "Luxembourgeoise", "Macédonienne",
  "Malgache", "Malaisienne", "Malawite", "Maldivienne", "Malienne", "Maltaise", "Marocaine",
  "Marshallaise", "Mauricienne", "Mauritanienne", "Mexicaine", "Micronésienne", "Moldave",
  "Monégasque", "Mongole", "Monténégrine", "Mozambicaine", "Namibienne", "Nauruane",
  "Népalaise", "Nicaraguayenne", "Nigerienne", "Nigériane", "Norvégienne", "Néo-zélandaise",
  "Omanaise", "Ougandaise", "Ouzbèke", "Pakistanaise", "Palauane", "Panaméenne",
  "Papouasienne", "Paraguayenne", "Néerlandaise", "Péruvienne", "Philippine", "Polonaise",
  "Portugaise", "Qatarienne", "Centrafricaine", "R.D.Congolaise", "Dominicaine", "Tchèque",
  "Roumaine", "Britannique", "Russe", "Rwandaise", "Christophienne", "Lucilienne",
  "Saint-marinaise", "Vincentaise", "Salomonaise", "Salvadorienne", "Samoane",
  "Santoméenne", "Sénégalaise", "Serbe", "Seychelloise", "Sierra-léonaise", "Singapourienne",
  "Slovaque", "Slovène", "Somalienne", "Soudanaise", "Sud-soudanaise", "Sri-lankaise",
  "Suédoise", "Suisse", "Surinamaise", "Syrienne", "Tadjike", "Tanzanienne", "Tchadienne",
  "Thaïlandaise", "Timoraise", "Togolaise", "Tonguienne", "Trinidadienne", "Tunisienne",
  "Turkmène", "Turque", "Tuvaluane", "Ukrainienne", "Uruguayenne", "Vanuatuane", "Vaticane",
  "Vénézuélienne", "Vietnamienne", "Yéménite", "Zambienne", "Zimbabwéenne"
];

// Indicatifs téléphoniques (liste complète)
export const phoneCodes = [
  "+1", "+7", "+20", "+27", "+30", "+31", "+32", "+33", "+34", "+36", "+39", "+40",
  "+41", "+44", "+45", "+46", "+47", "+48", "+49", "+51", "+52", "+53", "+54", "+55",
  "+56", "+57", "+58", "+60", "+61", "+62", "+63", "+64", "+65", "+66", "+81", "+82",
  "+84", "+86", "+90", "+91", "+92", "+93", "+94", "+95", "+98", "+211", "+212", "+213",
  "+214", "+216", "+218", "+220", "+221", "+222", "+223", "+224", "+225", "+226", "+227",
  "+228", "+229", "+230", "+231", "+232", "+233", "+234", "+235", "+236", "+237", "+238",
  "+239", "+240", "+241", "+242", "+243", "+244", "+245", "+246", "+247", "+248", "+249",
  "+250", "+251", "+252", "+253", "+254", "+255", "+256", "+257", "+258", "+260", "+261",
  "+262", "+263", "+264", "+265", "+266", "+267", "+268", "+269", "+290", "+291", "+297",
  "+298", "+299", "+350", "+351", "+352", "+353", "+354", "+355", "+356", "+357", "+358",
  "+359", "+370", "+371", "+372", "+373", "+374", "+375", "+376", "+377", "+378", "+379",
  "+380", "+381", "+382", "+383", "+385", "+386", "+387", "+389", "+420", "+421", "+423",
  "+500", "+501", "+502", "+503", "+504", "+505", "+506", "+507", "+508", "+509", "+590",
  "+591", "+592", "+593", "+594", "+595", "+596", "+597", "+598", "+599", "+670", "+672",
  "+673", "+674", "+675", "+676", "+677", "+678", "+679", "+680", "+681", "+682", "+683",
  "+685", "+686", "+687", "+688", "+689", "+690", "+691", "+692", "+850", "+852", "+853",
  "+855", "+856", "+880", "+886", "+960", "+961", "+962", "+963", "+964", "+965", "+966",
  "+967", "+968", "+970", "+971", "+972", "+973", "+974", "+975", "+976", "+977", "+992",
  "+993", "+994", "+995", "+996", "+998"
];